import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Roboto } from "next/font/google";
import "./globals.css";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/header";
import accountApiRequest from "@/apiRequests/account";

const roboto = Roboto({
  subsets: ["vietnamese"],
  weight: ["100", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken");
  let user = null;
  if (sessionToken) {
    const result = await accountApiRequest.me(sessionToken.value);
    user = result.payload.data;
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <Toaster position="top-right" richColors duration={3000} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider inititalSessionToken={sessionToken?.value} user={user}>
            <Header user={user} />
            {children}
            <SlideSession />
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
